<a href="https://colab.research.google.com/github/bearanha/WoMakersCode/blob/main/01_WoMakersCode_Python_para_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
l = [1, 2, 3, 4]
arr1= np.array(l)

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
np.zeros((2,2)) #o .zeros precisa de uma tupla
# primeiro elemento da tupla é uma linha, e o segundo colunas

array([[0., 0.],
       [0., 0.]])

In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
list(range(0,3))

[0, 1, 2]

In [11]:
arr_range = np.arange(1,11)
print (arr_range)
type(arr_range) # tipo array

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [15]:
np.random.random((6,3)) # também recebe tuplas
# por quê random.random? Porque np.random - é um módulo - e dentro dele haverá vários métodos (.random, .randint)

array([[0.48847424, 0.36545782, 0.16037708],
       [0.88080905, 0.74662132, 0.71283181],
       [0.18779879, 0.33777635, 0.82630005],
       [0.04731542, 0.50317623, 0.2572177 ],
       [0.36209861, 0.17676533, 0.63043551],
       [0.1622796 , 0.59140073, 0.16927338]])

## 2. Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios

In [19]:
array_int = np.random.randint(10, 31, size=(3,5)) #primeiro argumento é o valor mínimo (argumento que pode ser ocultado e o segundo argumento é sempre o limite máximo. a tupla sempre se referirá ao tamanho (ou vc pode chamar um size=)
array_int

array([[18, 12, 10, 10, 22],
       [12, 30, 26, 12, 24],
       [14, 18, 16, 17, 27]])

In [23]:
array_4 = np.arange(0, 92, 3) # aqui, o terceiro argumento do módulo np.range diz respeito ao valor que deve ser contado entre o número anterior e o próximo
array_4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90])

In [27]:
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 0], [1, 2]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d]) # array de três dimensões. meio que o máximo, uma vez que não temos 4 dimensões, mas existe. principalmente se vc for lidar com redes neurais
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [10, 11]],

       [[ 5,  6],
        [ 7,  8],
        [10, 11]],

       [[ 9,  0],
        [ 1,  2],
        [10, 11]]])