<a href="https://colab.research.google.com/github/bearanha/WoMakersCode/blob/main/NumPy_WoMakersCode_Python_para_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np


In [6]:
l = [1, 2, 3, 4]
arr1= np.array(l)

In [7]:
arr1

array([1, 2, 3, 4])

In [8]:
np.zeros((2,2)) #o .zeros precisa de uma tupla
# primeiro elemento da tupla é uma linha, e o segundo colunas

array([[0., 0.],
       [0., 0.]])

In [9]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
list(range(0,3))

[0, 1, 2]

In [11]:
arr_range = np.arange(1,11)
print (arr_range)
type(arr_range) # tipo array

[ 1  2  3  4  5  6  7  8  9 10]


numpy.ndarray

In [12]:
np.random.random((6,3)) # também recebe tuplas
# por quê random.random? Porque np.random - é um módulo - e dentro dele haverá vários métodos (.random, .randint)

array([[0.64701357, 0.66452547, 0.90298519],
       [0.61216042, 0.99795268, 0.41818096],
       [0.80790847, 0.45198232, 0.08028198],
       [0.57316437, 0.01842555, 0.89371185],
       [0.50004026, 0.97289527, 0.29081204],
       [0.17897338, 0.48765225, 0.04765051]])

## 2. Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios

In [13]:
array_int = np.random.randint(10, 31, size=(3,5)) #primeiro argumento é o valor mínimo (argumento que pode ser ocultado e o segundo argumento é sempre o limite máximo. a tupla sempre se referirá ao tamanho (ou vc pode chamar um size=)
array_int

array([[18, 20, 28, 14, 19],
       [26, 24, 17, 17, 24],
       [22, 16, 17, 20, 24]])

In [14]:
array_4 = np.arange(0, 92, 3) # aqui, o terceiro argumento do módulo np.range diz respeito ao valor que deve ser contado entre o número anterior e o próximo
array_4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90])

In [88]:
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 0], [1, 2]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d]) # array de três dimensões. meio que o máximo, uma vez que não temos 4 dimensões, mas existe. principalmente se vc for lidar com redes neurais
print(arr_3d)
print('')
print('*'*30)
print('')
other_3d = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print(other_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [1 2]]]

******************************

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Arrays e suas Dimensões


In [16]:
# SHAPE
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr.shape # descreve a array

(2, 4)

In [18]:
arr_2D = np.array([[1,2,3,0],[4,5,6,0], [9,9,9,9]])
# esse array terá três linhas e quatro colunas - cada lista que se passa é uma linha
arr_2D

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [9, 9, 9, 9]])

In [19]:
arr_2D.flatten()

array([1, 2, 3, 0, 4, 5, 6, 0, 9, 9, 9, 9])

In [20]:
arr2_2D = np.array([[3,4,2], [8, 11, 5]])
arr2_2D

array([[ 3,  4,  2],
       [ 8, 11,  5]])

In [21]:
arr2_2D.reshape((3,2)) # passa uma tupla como parâmetro

array([[ 3,  4],
       [ 2,  8],
       [11,  5]])

## Máscaras e Filtragens

In [22]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
mask = arr1 % 2 == 0 # uma condicional é inserida
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr1[mask] #Fancy Index - retorna os valores do array quando passada a máscara

array([ 2,  4,  6,  8, 10])

In [25]:
np.where(mask) # o np.where retorna os indexes onde estão posicionados aqueles elementos do arraay que tiveram a condição true

(array([1, 3, 5, 7, 9]),)

In [26]:
cartela_bingo = np.random.randint(10, 31, size=(4,4))
cartela_bingo

array([[30, 13, 23, 15],
       [26, 20, 24, 27],
       [28, 11, 30, 30],
       [22, 20, 10, 27]])

In [27]:
np.where(cartela_bingo % 3 == 0)
# Aqui o primeiro array pintado localiza linha e o segundo localiza coluna (por exemplo, linha 1 e coluna 2 aponta para 15)

(array([0, 0, 1, 1, 2, 2, 3]), array([0, 3, 2, 3, 2, 3, 3]))

In [28]:
np.where(cartela_bingo % 3 == 0)

(array([0, 0, 1, 1, 2, 2, 3]), array([0, 3, 2, 3, 2, 3, 3]))

In [29]:
np.where(cartela_bingo % 3 == 0, '', cartela_bingo)
# 2o argumento se refere pelo que será substituído o elemento caso a condição seja true e
# 3o argumento se refere à substituição no caso da condição ser false -
# Neste exemplo, quando se coloca o nome da variável em teste, significa que em caso negativo da comparação, nada deve ser feito
# Uma vez utilizada string vazias para a substituição, todo o array se torna tipo string

array([['', '13', '23', ''],
       ['26', '20', '', ''],
       ['28', '11', '', ''],
       ['22', '20', '10', '']], dtype='<U21')

## Adicionando e Removendo Dados do Array

In [30]:
# CONCATENANDO LINHAS
arrl1 = np.random.randint(10, size=(3,2))
arrl1

array([[6, 2],
       [4, 3],
       [6, 0]])

In [31]:
arrl2 = np.array([['Peras', 'Morangos']]) # é dtype='<U8' porque a maior string do array possui 8 caracteres
# prestar atenção que, para fechar o array que tenha 1 linha e duas colunas, como neste caso, é necessário colocar dois [[]]. Caso contrário, ele considera que só existe uma dimensão de uma linha
arrl2

# escrever "arrl2 = np.array([['Peras', 'Morangos']])" - com dois [[]] -, é o mesmo que "arrl2 = np.array(['Peras', 'Morangos']).reshape((1,2))"

array([['Peras', 'Morangos']], dtype='<U8')

In [32]:
np.concatenate((arrl1, arrl2))

array([['6', '2'],
       ['4', '3'],
       ['6', '0'],
       ['Peras', 'Morangos']], dtype='<U21')

In [33]:
# CONCATENANDO COLUNAS

arrc1 = np.array(['Uva', 'Abacaxi', 'Laranja']).reshape((3,1)) # o 'reshape' é necessário para que o shape entenda que se trata apenas de uma única coluna (3,1) e não de apenas 3 linhas (3)
arrc1

array([['Uva'],
       ['Abacaxi'],
       ['Laranja']], dtype='<U7')

In [34]:
fruits_array = np.concatenate((arrl1, arrc1), axis = 1) # axis = 0 linhas; axis = 1, colunas
fruits_array

array([['6', '2', 'Uva'],
       ['4', '3', 'Abacaxi'],
       ['6', '0', 'Laranja']], dtype='<U21')

In [35]:
# NP.DELETE
np.delete(fruits_array, 1, axis = 0)

array([['6', '2', 'Uva'],
       ['6', '0', 'Laranja']], dtype='<U21')

In [36]:
np.delete(fruits_array, 2, axis = 1)

# Caso delete sem axis, ela se torna um array de uma linha


array([['6', '2'],
       ['4', '3'],
       ['6', '0']], dtype='<U21')

## Cálculos com Array

In [44]:
# SOMAR .sum()
arr_sum = np.array([[1,2,3,0],[4,5,6,0], [9,9,9,9]])
arr_sum

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [9, 9, 9, 9]])

In [46]:
arr_sum.sum()

57

In [47]:
# SOMAR LINHAS
arr_sum.sum(axis=0) # estranhamente soma a linha como somaríamos colunas

array([14, 16, 18,  9])

In [49]:
# SOMAR COLUNAS
arr_sum.sum(axis=1) # estranhamente soma a coluna como somaríamos linhas

array([ 6, 15, 36])

## A Explicação para essa coisa estranha

Os dados que temos são a contabilização de acidentes de cada cliente em cada ano por uma empresa de seguros de carros.

As colunas representam cada cliente, enquanto as linhas se referem ao período de contratação. Ao somar colunas (axis = 1) teríamos a soma de todos os acidentes no ano. Enquanto se somarmos as linhas (axis = 0), teremos quantos acidentes cada cliente teve em todo tempo de contratação (do ano 1 ao 5)

In [51]:
arr_sum.min()

0

In [52]:
arr_sum.max()

9

In [54]:
arr_sum.max(axis = 0)

array([9, 9, 9, 9])

In [56]:
arr_sum.max(axis = 1)

array([3, 6, 9])

In [62]:
# MÉDIA
media_total = arr_sum.mean()
print(media_total)
print('*********')

media_linha = arr_sum.mean(axis = 0) # eg.: média do ano 05
print(media_linha)
print('*********')

media_coluna = arr_sum.mean(axis = 1) # eg.: média do cliente 1
print(media_coluna)

4.75
*********
[4.66666667 5.33333333 6.         3.        ]
*********
[1.5  3.75 9.  ]


In [65]:
# KEEPDIMS - mantém as mesmas dimensões
# MÉDIA
media_total = arr_sum.mean()
print(media_total)
print('*********')

media_linha = arr_sum.mean(axis = 0, keepdims = True) # eg.: média do ano 05
print(media_linha)
print('*********')

media_coluna = arr_sum.mean(axis = 1, keepdims = True) # eg.: média do cliente 1
print(media_coluna)

4.75
*********
[[4.66666667 5.33333333 6.         3.        ]]
*********
[[1.5 ]
 [3.75]
 [9.  ]]


In [70]:
# SOMA CUMULATIVA - cumsum
# quase uma soma fibonacci - cada dado se torna a soma do atual com o anterior
print(arr_sum)
print('*********')
arr_sum.cumsum(axis = 0)

[[1 2 3 0]
 [4 5 6 0]
 [9 9 9 9]]
*********


array([[ 1,  2,  3,  0],
       [ 5,  7,  9,  0],
       [14, 16, 18,  9]])

In [71]:
print(arr_sum)
print('*********')
arr_sum.cumsum(axis = 1)

[[1 2 3 0]
 [4 5 6 0]
 [9 9 9 9]]
*********


array([[ 1,  3,  6,  6],
       [ 4,  9, 15, 15],
       [ 9, 18, 27, 36]])

## Operações com Vetorização

In [73]:
# np.vectorize

arr_v = np.array(['Hello', 'meninas', 'coders'])
len(arr_v) > 5

False

In [75]:
vectorize_len = np.vectorize(len) # vetoriza um método de python 'len', no caso.
vectorize_len(arr_v) # como um for loop, passa em todos os elementos e considera o tamanho de cada um

array([5, 7, 6])

In [76]:
vectorize_len = np.vectorize(len)
vectorize_len(arr_v) > 5 # fica como a máscara, que aprendemos anteriormente

array([False,  True,  True])

In [78]:
def my_function(x):
  return x + 3

vec_my_function = np.vectorize(my_function) # vetorizando a função que criei com Python

original_array = np.array([1, 2, 3, 4, 5])

vec_new_array = vec_my_function(original_array)

print(vec_new_array)

[4 5 6 7 8]


In [79]:
# Broadcasting (transmissão)
broad_arr = np.array([[1, 2], [5, 6]])
broad_arr * 2

array([[ 2,  4],
       [10, 12]])

In [82]:
arr_3x3= np.array([[1,2],
                   [4, 5],
                   [7,8]])

arr_3x1 = np.array([1, 0, -1]).reshape((3,1))

print(arr_3x1)

[[ 1]
 [ 0]
 [-1]]


In [84]:
arr_3x3 + arr_3x1

array([[2, 3],
       [4, 5],
       [6, 7]])